In [125]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [126]:
df = pd.read_csv("diabetes_data_upload.csv")

In [127]:
df.head(5)

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [112]:
"""Fungsi untuk mengkategorikan setiap umur kedalam suatu kelompok:
- jika umur seseorang dari data diatas 45 tahun, maka masuk kategori 0
- jika umur seseorang dari data 22-45 tahun, maka masuk kategori 1
- jika umur seseorang dari data 11-21 tahun, maka masuk kategori 2
- selain dari itu masuk kategori 3"""
def change_age(x):
    if x > 45:
        return 0
    elif x > 21 and x <= 45:
        return 1
    elif x > 11 and x <= 21:
        return 2
    else:
        return 3

# Preprocessing data

In [128]:
#konversikan nilai pada kolom umur pada dataframe
df["Age"] = df["Age"].apply(change_age)

In [129]:
df.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0    1   Male       No        Yes                 No      Yes         No   
1    0   Male       No         No                 No      Yes         No   
2    1   Male      Yes         No                 No      Yes        Yes   
3    1   Male       No         No                Yes      Yes        Yes   
4    0   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [130]:
le = preprocessing.LabelEncoder()
df[df.columns] = df[df.columns].apply(le.fit_transform)

In [131]:
df.head()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0    1       1         0           1                   0         1   
1    0       1         0           0                   0         1   
2    1       1         1           0                   0         1   
3    1       1         0           0                   1         1   
4    0       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [132]:
X = df.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]].values
X

array([[1, 1, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 1, 1, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 1],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [133]:
y = df.iloc[:,[16]].values
y_1d = y.flatten()
y_1d

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,

In [134]:
"""import seluruh library yang digunakan untuk pengujian, seperti train_test_split, classification_report,
dan confusion_matrix"""
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import metrics

# Menggunakan Metode Naive Bayes

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y_1d, train_size = 0.8)

In [10]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

In [11]:
y_pred = classifier.predict(X_test)

In [12]:
score = metrics.accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.90      0.84        40
           1       0.93      0.84      0.89        64

    accuracy                           0.87       104
   macro avg       0.86      0.87      0.86       104
weighted avg       0.87      0.87      0.87       104



# Mengimport library decision tree


In [135]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

In [136]:
# split data training menjadi 0.8 dengan seed random 42
X_train, X_test, y_train, y_test = train_test_split(X, y_1d, train_size = 0.75, random_state=42)

In [137]:
# memanggil class decision tree classifier
clf = DecisionTreeClassifier(random_state=42)
clf = DecisionTreeClassifier(random_state=0)

# fitting menggunakan decision tree
clf = clf.fit(X_train, y_train)

# mempredikisi
clf_pred = clf.predict(X_test)

In [138]:
print(classification_report(y_test, clf_pred))
confusion_matrix(y_test, clf_pred)

              precision    recall  f1-score   support

           0       0.90      0.98      0.94        46
           1       0.99      0.94      0.96        84

    accuracy                           0.95       130
   macro avg       0.94      0.96      0.95       130
weighted avg       0.96      0.95      0.95       130



array([[45,  1],
       [ 5, 79]], dtype=int64)

In [139]:
"""import library pickle untuk menyimpan model dalam suatu file jika suatu saat model ini akan digunakan
dalam suatu sistem aplikasi"""
import pickle
pd.to_pickle(clf,"model_tree_diabetes.pkl")

In [84]:
# # menampung sementara data yang bertipe kategorikal
# obj_df = df.select_dtypes(include=['object']).copy()
# obj_df.head(5)

In [86]:
# from sklearn.preprocessing import LabelBinarizer

# lb = LabelBinarizer()

# for (columnName, columnData) in obj_df.iteritems():
#     obj_df[columnName] = lb.fit_transform(obj_df[columnName])

In [85]:
## memeriksa apakah ada nilai null pada dataframe
# obj_df['class'] = df['class']

In [67]:
yes=0
no=0
for i in y_test:
    if(i == 0):
        yes = yes + 1
    else:
        no = no + 1
print(yes/len(y_test))

0.35384615384615387


In [68]:
print(no/len(y_test))

0.6461538461538462


In [69]:
yes=0
no=0
for i in y_train:
    if(i == 0):
        yes = yes + 1
    else:
        no = no + 1
print(yes/len(y_train))

0.39487179487179486


In [70]:
print(no/len(y_train))

0.6051282051282051
